# Generated by Django 5.2.4 on 2025-07-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Create', 'Create'), ('Read', 'Read'), ('Update_Profile', 'Update_profile'), ('Login', 'Login'), ('Logout', 'Logout'), ('Failed_Login', 'Failed_Login'), ('Delete', 'Delete'), ('Other', 'Other')], max_length=20)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Success')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Users.users')),
            ],
        ),
    ]
