# Generated by Django 5.0.6 on 2025-07-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0005_logs_is_protected_alter_logs_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE', 'Delete'), ('DELETE_ALL_LOGS', 'Delete_all_logs'), ('DELETE_LOGS', 'Delete_log')], max_length=20),
        ),
    ]
