# Generated by Django 5.0.6 on 2025-08-04 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0006_alter_logs_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
        migrations.AddField(
            model_name='logs',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logs',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_recieve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE', 'Delete'), ('DELETE_ALL_LOGS', 'Delete_All_Logs'), ('DELETE_LOGS', 'Delete_log')], max_length=20),
        ),
    ]
