# Generated by Django 5.2.4 on 2025-08-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0007_remove_logs_user_logs_actor_user_logs_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='action_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
