# Generated by Django 5.2.4 on 2025-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0008_logs_action_title_logs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='new_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='old_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
