# Generated by Django 5.2.4 on 2025-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0009_logs_new_values_logs_old_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='old_values',
        ),
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE', 'Delete'), ('DELETE_ALL_LOGS', 'Delete_All_Logs'), ('DELETE_LOGS', 'Delete_log')], max_length=20),
        ),
    ]
