# Generated by Django 5.2.4 on 2025-09-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0010_remove_logs_new_values_remove_logs_old_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE User', 'Delete_user'), ('DEACTIVATE_USER', 'Deactivate_user'), ('DELETE_ALL_LOGS', 'Delete_All_Logs'), ('DELETE_LOGS', 'Delete_log')], max_length=20),
        ),
    ]
