# Generated by Django 5.2.4 on 2025-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0011_alter_logs_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE_User', 'Delete_user'), ('DEACTIVATE_USER', 'Deactivate_user'), ('DELETE_ALL_LOGS', 'Delete_All_Logs'), ('DELETE_LOGS', 'Delete_log')], max_length=20),
        ),
    ]
