# Generated by Django 5.2.4 on 2025-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0013_alter_logs_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE_USER', 'Delete_user'), ('DEACTIVATE_USER', 'Deactivate_user'), ('DELETE_ALL_LOGS', 'Delete_All_Logs'), ('DELETE_LOGS', 'Delete_log'), ('RESET_LOCK', 'Reset_user_lock')], max_length=20),
        ),
    ]
