# Generated by Django 5.2.4 on 2025-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
