# Generated by Django 5.0.6 on 2025-07-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
