# Generated by Django 5.0.6 on 2025-07-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
