# Generated by Django 5.2.4 on 2025-08-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_users_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_authenticated',
        ),
    ]
