# Generated by Django 5.2.4 on 2025-09-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_users_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_active',
            new_name='isActive',
        ),
    ]
