# Generated by Django 5.2.4 on 2025-09-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_is_active_users_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
