# Generated by Django 5.2.4 on 2025-09-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_isactive_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('admin', 'Admin')], default='normal', max_length=10),
        ),
    ]
