# Generated by Django 5.2.4 on 2025-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_num',
            field=models.IntegerField(default=0),
        ),
    ]
