# Generated by Django 5.2.4 on 2025-09-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_rename_is_staff_users_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField()),
                ('logs', models.JSONField(null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
