# Generated by Django 5.2.4 on 2025-07-19 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_alter_logs_action_status'),
        ('Users', '0002_alter_users_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='Success', max_length=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE_PROFILE', 'Update_profile'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed_Login'), ('DELETE', 'Delete'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Users.users'),
        ),
    ]
