# Generated by Django 5.2.4 on 2025-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0003_alter_logs_action_status_alter_logs_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE_PROFILE', 'Update_profile'), ('DELETE', 'Delete')], max_length=20),
        ),
    ]
