# Generated by Django 4.2.23 on 2025-07-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_logs_description_alter_logs_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='action_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10),
        ),
    ]
