# Generated by Django 5.0.6 on 2025-07-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Log_In', 'Log_in'), ('Log_out', 'Log_out')], max_length=20)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
