# Generated by Django 5.0.6 on 2025-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_logs',
            name='action_type',
            field=models.CharField(choices=[('Login', 'Log_in'), ('Logout', 'Log_out')], max_length=20),
        ),
    ]
