# Generated by Django 5.2.4 on 2025-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Auth', '0002_alter_auth_logs_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_logs',
            name='action_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
