# Generated by Django 5.2.4 on 2025-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Auth', '0003_auth_logs_action_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_logs',
            name='action_type',
            field=models.CharField(choices=[('Login', 'Log_in'), ('Logout', 'Log_out'), ('LOGIN_FAILED', 'Log_Failed')], max_length=20),
        ),
    ]
