# Generated by Django 5.2.4 on 2025-09-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Auth', '0004_alter_auth_logs_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_logs',
            name='action_type',
            field=models.CharField(choices=[('Login', 'Log_in'), ('Logout', 'Log_out'), ('LOGIN_FAILED', 'Log_Failed'), ('LOCK_USER', 'Lock')], max_length=20),
        ),
    ]
